import express from "express";
import authRoute from "./auth.route";
import cartRoute from "./cart.route";
import categoryRoute from "./category.route";
import collectionRoute from "./collection.route";
import couponRoute from "./coupon.route";
import creditCodeRoute from "./credit.code.route";
import flashSalesRoute from "./flas.sales.route";
import mediaRoute from "./media.route";
import orderAddressRoute from "./order.address.route";
import ordersRoute from "./orders.route";
import productRatingRoute from "./product.rating.route";
import productRoute from "./product.route";
import productVariationRoute from "./product.variation.route";
import relatedProductRoute from "./related.product.route";
import storeRoute from "./store.route";
import storeOrdersProductRoute from "./store.orders.product.route";
import storeOrdersRoute from "./store.orders.route";
import tagRoute from "./tag.route";
import userAddressRoute from "./user.address.route";
import userRoute from "./user.route";
import userWalletRoute from "./user.wallet.route";
import variationAttributesRoute from "./variation.attributes.route";
import vendorSettlementRoute from "./vendor.settlement.route";
import wishlistRoute from "./wishlist.route";
import withrawalRoute from "./withdrawal.route";
import postmanVariablesRoutes from "../../../postman_variables/index";

const router = express.Router();

router.use("/auth", authRoute);
router.use("/cart", cartRoute);
router.use("/category", categoryRoute);
router.use("/collection", collectionRoute);
router.use("/coupon", couponRoute);
router.use("/credit", creditCodeRoute);
router.use("/flashsales", flashSalesRoute);
router.use("/media", mediaRoute);
router.use("/order-address", orderAddressRoute);

router.use("/orders", ordersRoute);
router.use("/product-rating", productRatingRoute);
router.use("/product", productRoute);
router.use("/variation", productVariationRoute);
router.use("/related-product", relatedProductRoute);
router.use("/store", storeRoute);
router.use("/sub-orders-products", storeOrdersProductRoute);
router.use("/sub-orders", storeOrdersRoute);
router.use("/tag", tagRoute);
router.use("/user-address", userAddressRoute);
router.use("/user", userRoute);
router.use("/wallet", userWalletRoute);
router.use("/attributes", variationAttributesRoute);
router.use("/settlement", vendorSettlementRoute);
router.use("/wishlist", wishlistRoute);
router.use("/withdrawal", withrawalRoute);

// Just postman variables
router.use("/postman_variables", postmanVariablesRoutes);
export default router;
